# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calligraphycomparisonmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1343, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comparison_main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.comparison_main_tab.setGeometry(QtCore.QRect(339, 9, 1001, 721))
        self.comparison_main_tab.setObjectName("comparison_main_tab")
        self.whole_comparison_tab = QtWidgets.QWidget()
        self.whole_comparison_tab.setObjectName("whole_comparison_tab")
        self.whole_main_tabwidget = QtWidgets.QTabWidget(self.whole_comparison_tab)
        self.whole_main_tabwidget.setGeometry(QtCore.QRect(-1, 9, 1001, 681))
        self.whole_main_tabwidget.setObjectName("whole_main_tabwidget")
        self.whole_cr_tab = QtWidgets.QWidget()
        self.whole_cr_tab.setObjectName("whole_cr_tab")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.whole_cr_tab)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 821, 651))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 819, 649))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.cover_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_3)
        self.cover_gview.setGeometry(QtCore.QRect(-10, 0, 831, 651))
        self.cover_gview.setObjectName("cover_gview")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.whole_cr_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(830, 90, 160, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.maxcr_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.maxcr_label.setObjectName("maxcr_label")
        self.horizontalLayout.addWidget(self.maxcr_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mizi_rbtn = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.mizi_rbtn.setObjectName("mizi_rbtn")
        self.verticalLayout_2.addWidget(self.mizi_rbtn)
        self.jiugong_rbtn = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.jiugong_rbtn.setObjectName("jiugong_rbtn")
        self.verticalLayout_2.addWidget(self.jiugong_rbtn)
        self.cr_calculate_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.cr_calculate_btn.setObjectName("cr_calculate_btn")
        self.verticalLayout_2.addWidget(self.cr_calculate_btn)
        self.whole_main_tabwidget.addTab(self.whole_cr_tab, "")
        self.whole_goc_tab = QtWidgets.QWidget()
        self.whole_goc_tab.setObjectName("whole_goc_tab")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.whole_goc_tab)
        self.scrollArea_4.setGeometry(QtCore.QRect(10, 10, 401, 311))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 399, 309))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.cog_template_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_4)
        self.cog_template_gview.setGeometry(QtCore.QRect(0, 0, 401, 311))
        self.cog_template_gview.setObjectName("cog_template_gview")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.whole_goc_tab)
        self.scrollArea_5.setGeometry(QtCore.QRect(430, 10, 401, 311))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 399, 309))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.cog_target_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_5)
        self.cog_target_gview.setGeometry(QtCore.QRect(0, 0, 401, 311))
        self.cog_target_gview.setObjectName("cog_target_gview")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.whole_goc_tab)
        self.scrollArea_6.setGeometry(QtCore.QRect(10, 360, 401, 291))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 399, 289))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.cog_comparison_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_6)
        self.cog_comparison_gview.setGeometry(QtCore.QRect(0, 0, 401, 291))
        self.cog_comparison_gview.setObjectName("cog_comparison_gview")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.whole_goc_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(470, 570, 146, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cog_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cog_btn.setObjectName("cog_btn")
        self.verticalLayout_3.addWidget(self.cog_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.whole_goc_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 320, 191, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.template_cog_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.template_cog_label.setObjectName("template_cog_label")
        self.horizontalLayout_2.addWidget(self.template_cog_label)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.whole_goc_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(540, 320, 191, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.target_cog_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.target_cog_label.setObjectName("target_cog_label")
        self.horizontalLayout_3.addWidget(self.target_cog_label)
        self.whole_main_tabwidget.addTab(self.whole_goc_tab, "")
        self.whole_ch_tab = QtWidgets.QWidget()
        self.whole_ch_tab.setObjectName("whole_ch_tab")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.whole_ch_tab)
        self.scrollArea_7.setGeometry(QtCore.QRect(10, 10, 421, 401))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 419, 399))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.template_ch_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_7)
        self.template_ch_gview.setGeometry(QtCore.QRect(0, 0, 421, 401))
        self.template_ch_gview.setObjectName("template_ch_gview")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.scrollArea_8 = QtWidgets.QScrollArea(self.whole_ch_tab)
        self.scrollArea_8.setGeometry(QtCore.QRect(470, 10, 421, 401))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 419, 399))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.target_ch_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_8)
        self.target_ch_gview.setGeometry(QtCore.QRect(0, 0, 421, 401))
        self.target_ch_gview.setObjectName("target_ch_gview")
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.whole_ch_tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 569, 160, 32))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.convexhull_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.convexhull_btn.setObjectName("convexhull_btn")
        self.verticalLayout_4.addWidget(self.convexhull_btn)
        self.formLayoutWidget = QtWidgets.QWidget(self.whole_ch_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(230, 440, 201, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.temp_convex_area_ratio_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.temp_convex_area_ratio_label.setObjectName("temp_convex_area_ratio_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temp_convex_area_ratio_label)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.temp_valid_area_ratio_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.temp_valid_area_ratio_label.setObjectName("temp_valid_area_ratio_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temp_valid_area_ratio_label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.whole_ch_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(690, 440, 201, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.targ_convex_area_ratio_label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.targ_convex_area_ratio_label_2.setObjectName("targ_convex_area_ratio_label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.targ_convex_area_ratio_label_2)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.targ_valid_area_ratio_label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.targ_valid_area_ratio_label_2.setObjectName("targ_valid_area_ratio_label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.targ_valid_area_ratio_label_2)
        self.label_10 = QtWidgets.QLabel(self.whole_ch_tab)
        self.label_10.setGeometry(QtCore.QRect(170, 420, 111, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.whole_ch_tab)
        self.label_11.setGeometry(QtCore.QRect(620, 420, 111, 16))
        self.label_11.setObjectName("label_11")
        self.whole_main_tabwidget.addTab(self.whole_ch_tab, "")
        self.whole_histogram_tab = QtWidgets.QWidget()
        self.whole_histogram_tab.setObjectName("whole_histogram_tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(60, 570, 160, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.project_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.project_btn.setObjectName("project_btn")
        self.verticalLayout_5.addWidget(self.project_btn)
        self.label_12 = QtWidgets.QLabel(self.whole_histogram_tab)
        self.label_12.setGeometry(QtCore.QRect(20, 140, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.whole_histogram_tab)
        self.label_13.setGeometry(QtCore.QRect(20, 380, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.whole_histogram_tab)
        self.label_14.setGeometry(QtCore.QRect(190, 540, 111, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.whole_histogram_tab)
        self.label_15.setGeometry(QtCore.QRect(650, 540, 111, 16))
        self.label_15.setObjectName("label_15")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(230, 570, 121, 51))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.temp_x_mean_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.temp_x_mean_label.setObjectName("temp_x_mean_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temp_x_mean_label)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(350, 570, 121, 51))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.temp_y_mean_label = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.temp_y_mean_label.setObjectName("temp_y_mean_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temp_y_mean_label)
        self.gridLayoutWidget = QtWidgets.QWidget(self.whole_histogram_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 0, 391, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.temp_x_glayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.temp_x_glayout.setContentsMargins(0, 0, 0, 0)
        self.temp_x_glayout.setObjectName("temp_x_glayout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(510, 0, 391, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.targ_x_glayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.targ_x_glayout.setContentsMargins(0, 0, 0, 0)
        self.targ_x_glayout.setObjectName("targ_x_glayout")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(70, 280, 391, 261))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.temp_y_glayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.temp_y_glayout.setContentsMargins(0, 0, 0, 0)
        self.temp_y_glayout.setObjectName("temp_y_glayout")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(510, 280, 391, 261))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.targ_y_glayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.targ_y_glayout.setContentsMargins(0, 0, 0, 0)
        self.targ_y_glayout.setObjectName("targ_y_glayout")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(630, 570, 121, 51))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.targ_y_mean_label = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.targ_y_mean_label.setObjectName("targ_y_mean_label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.targ_y_mean_label)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(510, 570, 121, 51))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.targ_x_mean_label = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.targ_x_mean_label.setObjectName("targ_x_mean_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.targ_x_mean_label)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.whole_histogram_tab)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(800, 550, 160, 80))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_26.setObjectName("label_26")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.variance_x_label = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.variance_x_label.setObjectName("variance_x_label")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.variance_x_label)
        self.variance_y_label = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.variance_y_label.setObjectName("variance_y_label")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.variance_y_label)
        self.whole_main_tabwidget.addTab(self.whole_histogram_tab, "")
        self.comparison_main_tab.addTab(self.whole_comparison_tab, "")
        self.radical_comparison_tab = QtWidgets.QWidget()
        self.radical_comparison_tab.setObjectName("radical_comparison_tab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.radical_comparison_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 160, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stroke_layout_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.stroke_layout_btn.setObjectName("stroke_layout_btn")
        self.verticalLayout_6.addWidget(self.stroke_layout_btn)
        self.scrollArea_9 = QtWidgets.QScrollArea(self.radical_comparison_tab)
        self.scrollArea_9.setGeometry(QtCore.QRect(180, 20, 400, 400))
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 398, 398))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.template_strokes_layout_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_9)
        self.template_strokes_layout_gview.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.template_strokes_layout_gview.setObjectName("template_strokes_layout_gview")
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.scrollArea_10 = QtWidgets.QScrollArea(self.radical_comparison_tab)
        self.scrollArea_10.setGeometry(QtCore.QRect(590, 20, 400, 400))
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 398, 398))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.target_strokes_layout_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_10)
        self.target_strokes_layout_gview.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.target_strokes_layout_gview.setObjectName("target_strokes_layout_gview")
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_10)
        self.label_27 = QtWidgets.QLabel(self.radical_comparison_tab)
        self.label_27.setGeometry(QtCore.QRect(330, 430, 101, 16))
        self.label_27.setObjectName("label_27")
        self.label_33 = QtWidgets.QLabel(self.radical_comparison_tab)
        self.label_33.setGeometry(QtCore.QRect(740, 430, 101, 16))
        self.label_33.setObjectName("label_33")
        self.comparison_main_tab.addTab(self.radical_comparison_tab, "")
        self.stroke_comparison_tab = QtWidgets.QWidget()
        self.stroke_comparison_tab.setObjectName("stroke_comparison_tab")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.stroke_comparison_tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 131, 461))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_7)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.strokes_cr_listview = QtWidgets.QListView(self.verticalLayoutWidget_7)
        self.strokes_cr_listview.setObjectName("strokes_cr_listview")
        self.verticalLayout_7.addWidget(self.strokes_cr_listview)
        self.stroke_main_tabwidget = QtWidgets.QTabWidget(self.stroke_comparison_tab)
        self.stroke_main_tabwidget.setGeometry(QtCore.QRect(130, 10, 851, 681))
        self.stroke_main_tabwidget.setObjectName("stroke_main_tabwidget")
        self.stroke_cr_tab = QtWidgets.QWidget()
        self.stroke_cr_tab.setObjectName("stroke_cr_tab")
        self.scrollArea_11 = QtWidgets.QScrollArea(self.stroke_cr_tab)
        self.scrollArea_11.setGeometry(QtCore.QRect(10, 10, 600, 600))
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName("scrollArea_11")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 598, 598))
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.strokes_cr_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_11)
        self.strokes_cr_gview.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.strokes_cr_gview.setObjectName("strokes_cr_gview")
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_11)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.stroke_cr_tab)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(640, 10, 201, 161))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_29.setObjectName("label_29")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.strokes_cr_label = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.strokes_cr_label.setObjectName("strokes_cr_label")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.strokes_cr_label)
        self.strokes_cr_btn = QtWidgets.QPushButton(self.formLayoutWidget_8)
        self.strokes_cr_btn.setObjectName("strokes_cr_btn")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.strokes_cr_btn)
        self.stroke_main_tabwidget.addTab(self.stroke_cr_tab, "")
        self.stroke_segment_tab = QtWidgets.QWidget()
        self.stroke_segment_tab.setObjectName("stroke_segment_tab")
        self.scrollArea_12 = QtWidgets.QScrollArea(self.stroke_segment_tab)
        self.scrollArea_12.setGeometry(QtCore.QRect(10, 10, 261, 241))
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollArea_12.setObjectName("scrollArea_12")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 259, 239))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_12)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 261, 241))
        self.graphicsView.setObjectName("graphicsView")
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_12)
        self.scrollArea_13 = QtWidgets.QScrollArea(self.stroke_segment_tab)
        self.scrollArea_13.setGeometry(QtCore.QRect(10, 290, 261, 241))
        self.scrollArea_13.setWidgetResizable(True)
        self.scrollArea_13.setObjectName("scrollArea_13")
        self.scrollAreaWidgetContents_13 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_13.setGeometry(QtCore.QRect(0, 0, 259, 239))
        self.scrollAreaWidgetContents_13.setObjectName("scrollAreaWidgetContents_13")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_13)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 261, 241))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.scrollArea_13.setWidget(self.scrollAreaWidgetContents_13)
        self.scrollArea_14 = QtWidgets.QScrollArea(self.stroke_segment_tab)
        self.scrollArea_14.setGeometry(QtCore.QRect(310, 10, 531, 441))
        self.scrollArea_14.setWidgetResizable(True)
        self.scrollArea_14.setObjectName("scrollArea_14")
        self.scrollAreaWidgetContents_14 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_14.setGeometry(QtCore.QRect(0, 0, 529, 439))
        self.scrollAreaWidgetContents_14.setObjectName("scrollAreaWidgetContents_14")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_14)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 0, 531, 441))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.scrollArea_14.setWidget(self.scrollAreaWidgetContents_14)
        self.label_30 = QtWidgets.QLabel(self.stroke_segment_tab)
        self.label_30.setGeometry(QtCore.QRect(100, 260, 60, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.stroke_segment_tab)
        self.label_31.setGeometry(QtCore.QRect(100, 540, 60, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.stroke_segment_tab)
        self.label_32.setGeometry(QtCore.QRect(560, 460, 81, 16))
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(self.stroke_segment_tab)
        self.pushButton.setGeometry(QtCore.QRect(70, 570, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.listView_2 = QtWidgets.QListView(self.stroke_segment_tab)
        self.listView_2.setGeometry(QtCore.QRect(310, 480, 171, 161))
        self.listView_2.setObjectName("listView_2")
        self.stroke_main_tabwidget.addTab(self.stroke_segment_tab, "")
        self.comparison_main_tab.addTab(self.stroke_comparison_tab, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 100))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_template_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_template_btn.setObjectName("open_template_btn")
        self.verticalLayout.addWidget(self.open_template_btn)
        self.open_target_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_target_btn.setObjectName("open_target_btn")
        self.verticalLayout.addWidget(self.open_target_btn)
        self.exit_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout.addWidget(self.exit_btn)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 130, 321, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.template_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.template_gview.setGeometry(QtCore.QRect(0, 0, 321, 281))
        self.template_gview.setObjectName("template_gview")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 110, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 420, 60, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 440, 321, 281))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 279))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.target_gview = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        self.target_gview.setGeometry(QtCore.QRect(0, 0, 321, 281))
        self.target_gview.setObjectName("target_gview")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1343, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comparison_main_tab.setCurrentIndex(2)
        self.whole_main_tabwidget.setCurrentIndex(3)
        self.stroke_main_tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Max CR:"))
        self.maxcr_label.setText(_translate("MainWindow", "0.0"))
        self.mizi_rbtn.setText(_translate("MainWindow", "Mizi"))
        self.jiugong_rbtn.setText(_translate("MainWindow", "JiuGong"))
        self.cr_calculate_btn.setText(_translate("MainWindow", "Calculate"))
        self.whole_main_tabwidget.setTabText(self.whole_main_tabwidget.indexOf(self.whole_cr_tab), _translate("MainWindow", "Coverage Rate"))
        self.cog_btn.setText(_translate("MainWindow", "Center of Gravity"))
        self.label_4.setText(_translate("MainWindow", "COG:"))
        self.template_cog_label.setText(_translate("MainWindow", "(0, 0)"))
        self.label_5.setText(_translate("MainWindow", "COG:"))
        self.target_cog_label.setText(_translate("MainWindow", "(0, 0)"))
        self.whole_main_tabwidget.setTabText(self.whole_main_tabwidget.indexOf(self.whole_goc_tab), _translate("MainWindow", "Gravity of Center"))
        self.convexhull_btn.setText(_translate("MainWindow", "Convex hull"))
        self.label_6.setText(_translate("MainWindow", "Convex hull \n"
" area ratio:"))
        self.temp_convex_area_ratio_label.setText(_translate("MainWindow", "0.0"))
        self.label_8.setText(_translate("MainWindow", "Valid pixels \n"
" area ratio:"))
        self.temp_valid_area_ratio_label.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "Convex hull \n"
" area ratio:"))
        self.targ_convex_area_ratio_label_2.setText(_translate("MainWindow", "0.0"))
        self.label_9.setText(_translate("MainWindow", "Valid pixels \n"
" area ratio:"))
        self.targ_valid_area_ratio_label_2.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "Template image"))
        self.label_11.setText(_translate("MainWindow", "Target image"))
        self.whole_main_tabwidget.setTabText(self.whole_main_tabwidget.indexOf(self.whole_ch_tab), _translate("MainWindow", "Convex hull"))
        self.project_btn.setText(_translate("MainWindow", "Project"))
        self.label_12.setText(_translate("MainWindow", "X："))
        self.label_13.setText(_translate("MainWindow", "Y："))
        self.label_14.setText(_translate("MainWindow", "Template Image"))
        self.label_15.setText(_translate("MainWindow", "Target Image"))
        self.label_16.setText(_translate("MainWindow", "X axis "))
        self.label_20.setText(_translate("MainWindow", "Mean:"))
        self.temp_x_mean_label.setText(_translate("MainWindow", "0.0"))
        self.label_17.setText(_translate("MainWindow", "Y axis "))
        self.label_21.setText(_translate("MainWindow", "Mean:"))
        self.temp_y_mean_label.setText(_translate("MainWindow", "0.0"))
        self.label_18.setText(_translate("MainWindow", "Y axis "))
        self.label_22.setText(_translate("MainWindow", "Mean:"))
        self.targ_y_mean_label.setText(_translate("MainWindow", "0.0"))
        self.label_19.setText(_translate("MainWindow", "X axis "))
        self.label_23.setText(_translate("MainWindow", "Mean:"))
        self.targ_x_mean_label.setText(_translate("MainWindow", "0.0"))
        self.label_24.setText(_translate("MainWindow", "Variance"))
        self.label_25.setText(_translate("MainWindow", "X-axis:"))
        self.label_26.setText(_translate("MainWindow", "Y-axis:"))
        self.variance_x_label.setText(_translate("MainWindow", "0.0"))
        self.variance_y_label.setText(_translate("MainWindow", "0.0"))
        self.whole_main_tabwidget.setTabText(self.whole_main_tabwidget.indexOf(self.whole_histogram_tab), _translate("MainWindow", "Histogram"))
        self.comparison_main_tab.setTabText(self.comparison_main_tab.indexOf(self.whole_comparison_tab), _translate("MainWindow", "Whole Comparison"))
        self.stroke_layout_btn.setText(_translate("MainWindow", "Strokes Layout"))
        self.label_27.setText(_translate("MainWindow", "Template image"))
        self.label_33.setText(_translate("MainWindow", "Target image"))
        self.comparison_main_tab.setTabText(self.comparison_main_tab.indexOf(self.radical_comparison_tab), _translate("MainWindow", "Radical Comparison"))
        self.label_28.setText(_translate("MainWindow", "Strokes:"))
        self.label_29.setText(_translate("MainWindow", "Max CR:"))
        self.strokes_cr_label.setText(_translate("MainWindow", "0.0"))
        self.strokes_cr_btn.setText(_translate("MainWindow", "Calculate"))
        self.stroke_main_tabwidget.setTabText(self.stroke_main_tabwidget.indexOf(self.stroke_cr_tab), _translate("MainWindow", "Coverage Rate"))
        self.label_30.setText(_translate("MainWindow", "Template"))
        self.label_31.setText(_translate("MainWindow", "Target"))
        self.label_32.setText(_translate("MainWindow", "Comparison"))
        self.pushButton.setText(_translate("MainWindow", "Segment"))
        self.stroke_main_tabwidget.setTabText(self.stroke_main_tabwidget.indexOf(self.stroke_segment_tab), _translate("MainWindow", "Segmentation"))
        self.comparison_main_tab.setTabText(self.comparison_main_tab.indexOf(self.stroke_comparison_tab), _translate("MainWindow", "Stroke Comparison"))
        self.open_template_btn.setText(_translate("MainWindow", "Open Template"))
        self.open_target_btn.setText(_translate("MainWindow", "Open Target"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.label_2.setText(_translate("MainWindow", "Target"))

